// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class DaysOfWeek
{
    public int Id { get; set; }

    public string DayName { get; set; }

    public string ShortName { get; set; }

    public virtual ICollection<DietDay> DietDays { get; set; } = new List<DietDay>();
}