// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class DietDay
{
    public int Id { get; set; }

    public long IdDiet { get; set; }

    public int IdDay { get; set; }

    public virtual DaysOfWeek IdDayNavigation { get; set; }

    public virtual Diet IdDietNavigation { get; set; }
}