// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class Diet
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public long IdNutritionist { get; set; }

    public long IdPatient { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<DietDay> DietDays { get; set; } = new List<DietDay>();

    public virtual UserInfo IdNutritionistNavigation { get; set; }

    public virtual UserInfo IdPatientNavigation { get; set; }

    public virtual ICollection<Meal> Meals { get; set; } = new List<Meal>();
}