// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class Food
{
    public long Id { get; set; }

    public string Name { get; set; }

    public double Quantity { get; set; }

    public long IdUnitMeasurement { get; set; }

    public double Carb { get; set; }

    public double Protein { get; set; }

    public double Fat { get; set; }

    public virtual UnitMeasurement IdUnitMeasurementNavigation { get; set; }

    public virtual ICollection<ItemsPlan> ItemsPlans { get; set; } = new List<ItemsPlan>();

    public virtual ICollection<Snack> Snacks { get; set; } = new List<Snack>();
}