// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class FoodNutritionInfo
{
    public long Id { get; set; }

    public long IdNutritionInfo { get; set; }

    public double? Carb { get; set; }

    public double? CarbTotal { get; set; }

    public double? Lipids { get; set; }

    public double? Moisture { get; set; }

    public double? Proteins { get; set; }

    public double? Fiber { get; set; }

    public double? Alcohol { get; set; }

    public double? Ash { get; set; }

    public double? Cholesterol { get; set; }

    public double? TotalSaturedFatty { get; set; }

    public double? TotalMonounsaturedFatty { get; set; }

    public double? TotalPolyunsaturedFatty { get; set; }

    public double? TransFatty { get; set; }

    public double? Calcium { get; set; }

    public double? Iron { get; set; }

    public double? Sodium { get; set; }

    public double? Magnesium { get; set; }

    public double? Phosphor { get; set; }

    public double? Potassium { get; set; }

    public double? Manganese { get; set; }

    public double? Zinc { get; set; }

    public double? Copper { get; set; }

    public double? Selenium { get; set; }

    public double? VitaminA { get; set; }

    public double? VitaminD { get; set; }

    public double? VitaminE { get; set; }

    public double? Thiamine { get; set; }

    public double? Riboflavin { get; set; }

    public double? Niacin { get; set; }

    public double? VitaminB6 { get; set; }

    public double? VitaminB12 { get; set; }

    public double? VitaminC { get; set; }

    public double? Folate { get; set; }

    public double? AddedSalt { get; set; }

    public double? AddedSugar { get; set; }

    public long IdUnitMeasurement { get; set; }

    public long? Quantity { get; set; }

    public virtual ICollection<Food> Foods { get; set; } = new List<Food>();

    public virtual UnitMeasurement IdUnitMeasurementNavigation { get; set; }
}