// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class ItemsPlan
{
    public long Id { get; set; }

    public long IdPlan { get; set; }

    public long IdFood { get; set; }

    public long Quantity { get; set; }

    public virtual Food IdFoodNavigation { get; set; }

    public virtual PlanDiet IdPlanNavigation { get; set; }
}