// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class Meal
{
    public long Id { get; set; }

    public long IdUser { get; set; }

    public DateTime Appointment { get; set; }

    public string Observation { get; set; }

    public int? Status { get; set; }

    public long? IdTypeSnack { get; set; }

    public bool? IsTemplate { get; set; }

    public long? IdDiet { get; set; }

    public virtual Diet IdDietNavigation { get; set; }

    public virtual TypeSnack IdTypeSnackNavigation { get; set; }

    public virtual UserInfo IdUserNavigation { get; set; }

    public virtual ICollection<Snack> Snacks { get; set; } = new List<Snack>();
}