// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class PasswordResetCode
{
    public long Id { get; set; }

    public long IdUser { get; set; }

    public string VerificationCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool IsUsed { get; set; }

    public virtual UserInfo IdUserNavigation { get; set; }
}