// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class PlanDiet
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long IdNutricionist { get; set; }

    public virtual UserInfo IdNutricionistNavigation { get; set; }

    public virtual ICollection<ItemsPlan> ItemsPlans { get; set; } = new List<ItemsPlan>();
}