// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class Snack
{
    public long Id { get; set; }

    public long IdFood { get; set; }

    public long IdUser { get; set; }

    public long IdTypeSnack { get; set; }

    public DateTime? Appointment { get; set; }

    public virtual Food IdFoodNavigation { get; set; }

    public virtual TypeSnack IdTypeSnackNavigation { get; set; }

    public virtual UserInfo IdUserNavigation { get; set; }
}