// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class Snack
{
    public long Id { get; set; }

    public long IdFood { get; set; }

    public long IdTypeSnack { get; set; }

    public DateTime? Appointment { get; set; }

    public double? Quantity { get; set; }

    public long? IdMeal { get; set; }

    public long? IdUnitMeasurement { get; set; }

    public long? CreatedBy { get; set; }

    public long? UpdatedBy { get; set; }

    public virtual UserInfo CreatedByNavigation { get; set; }

    public virtual Food IdFoodNavigation { get; set; }

    public virtual Meal IdMealNavigation { get; set; }

    public virtual TypeSnack IdTypeSnackNavigation { get; set; }

    public virtual UnitMeasurement IdUnitMeasurementNavigation { get; set; }

    public virtual UserInfo UpdatedByNavigation { get; set; }
}