// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class StatusUser
{
    public long Id { get; set; }

    public long IdNutricionist { get; set; }

    public long IdStatus { get; set; }

    public long IdUser { get; set; }

    public virtual UserInfo IdNutricionistNavigation { get; set; }

    public virtual Status IdStatusNavigation { get; set; }

    public virtual UserInfo IdUserNavigation { get; set; }
}