// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class UserPatientLink
{
    public long Id { get; set; }

    public long IdNutritionist { get; set; }

    public long IdPatient { get; set; }

    public bool IsCurrentNutritionist { get; set; }

    public int LinkStatus { get; set; }

    public virtual UserInfo IdNutritionistNavigation { get; set; }

    public virtual UserInfo IdPatientNavigation { get; set; }
}