// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalancedLife.Domain.Entities;

public partial class UserInfo
{
    public long Id { get; set; }

    public string Name { get; set; }

    public DateTime Birth { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string UrlImage { get; set; }

    public string Gender { get; set; }

    public string Cpf { get; set; }

    public string Street { get; set; }

    public long? Number { get; set; }

    public string ZipCode { get; set; }

    public long? IdCity { get; set; }

    public long? IdUserRole { get; set; }

    public string PhoneNumber { get; set; }

    public string Instagram { get; set; }

    public string Facebook { get; set; }

    public string Whatsapp { get; set; }

    public DateTime? ExpirationLicence { get; set; }

    public bool IsCompleteProfile { get; set; }

    public string District { get; set; }

    public virtual ICollection<Body> Bodies { get; set; } = new List<Body>();

    public virtual City IdCityNavigation { get; set; }

    public virtual UserRole IdUserRoleNavigation { get; set; }

    public virtual ICollection<Meal> Meals { get; set; } = new List<Meal>();

    public virtual ICollection<PasswordResetCode> PasswordResetCodes { get; set; } = new List<PasswordResetCode>();

    public virtual ICollection<PlanDiet> PlanDiets { get; set; } = new List<PlanDiet>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<Snack> SnackCreatedByNavigations { get; set; } = new List<Snack>();

    public virtual ICollection<Snack> SnackUpdatedByNavigations { get; set; } = new List<Snack>();

    public virtual ICollection<StatusUser> StatusUserIdNutricionistNavigations { get; set; } = new List<StatusUser>();

    public virtual ICollection<StatusUser> StatusUserIdUserNavigations { get; set; } = new List<StatusUser>();

    public virtual ICollection<UserPatientLink> UserPatientLinkIdNutritionistNavigations { get; set; } = new List<UserPatientLink>();

    public virtual ICollection<UserPatientLink> UserPatientLinkIdPatientNavigations { get; set; } = new List<UserPatientLink>();
}